# Generated by Django 3.1.7 on 2021-03-27 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210327_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagelink', to='auctions.image'),
        ),
    ]
