# Generated by Django 3.1.7 on 2021-03-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210327_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='link',
            new_name='Imagelink',
        ),
    ]
