# Generated by Django 3.1.7 on 2021-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210329_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Imagelink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Textdes',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
