# Generated by Django 3.1.7 on 2021-03-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210329_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Luser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Creator', to='auctions.user'),
            preserve_default=False,
        ),
    ]
