# Generated by Django 3.1.7 on 2021-03-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210330_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='Seller',
        ),
    ]
