# Generated by Django 3.1.7 on 2021-03-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auction_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='Auction_b',
        ),
        migrations.AddField(
            model_name='bids',
            name='Listing_b',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='StartingBid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
