# Generated by Django 3.1.7 on 2021-04-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210330_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='CurrentBid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
