# Generated by Django 3.1.7 on 2021-05-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
